### ISSUE TITLE
Add Table Operations to allow reading data via IceLake

### ISSUE THREAD

**Issue by Xuanwo** [icelake-io/icelake#26]
icelake 0.0.1 added most types that we need to load table metadata. We need to implement table operations to allow users reading data via us.

## Tasks

- [x] Get current table metadata
- [ ] Get all snapshots of current table metadata
- [ ] Get all manifest lists from current snapshot
- [x] https://github.com/icelake-io/icelake/pull/31

## Notes

- We will not add partition support before v0.1, so we can ignore partition spec and sorting order.
- API should be polished after.

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
