### ISSUE TITLE
Tracking issues of IceLake v0.0.1

### ISSUE THREAD

**Issue by Xuanwo** [icelake-io/icelake#4]
Part of https://github.com/icelake-io/icelake/issues/1

## Tasks

- [x] https://github.com/icelake-io/icelake/pull/3
- [x] https://github.com/icelake-io/icelake/pull/5
- [x] https://github.com/icelake-io/icelake/pull/6
- [x] https://github.com/icelake-io/icelake/pull/8
- [x] https://github.com/icelake-io/icelake/pull/9
- [x] https://github.com/icelake-io/icelake/pull/10
- [x] https://github.com/icelake-io/icelake/pull/11
- [x] https://github.com/icelake-io/icelake/pull/12
- [x] https://github.com/icelake-io/icelake/pull/16
- [x] https://github.com/icelake-io/icelake/pull/17
- [x] https://github.com/icelake-io/icelake/pull/19
- [x] https://github.com/icelake-io/icelake/pull/20
- [x] Integrate with [OpenDAL](https://github.com/apache/incubator-opendal) for IO
- [x] https://github.com/icelake-io/icelake/pull/18
- [x] https://github.com/icelake-io/icelake/pull/21

## Notes

- Schema Evolution is not supported for now. 
- Struct Default Value is not supported

**Comment by Xuanwo** [comment]
I have add a simple table under `testdata/`, our first milestone is able to read data from thath.

**Comment by Xuanwo** [comment]
We will release 0.0.1 first to make integrate start first!
